# Generated by Django 4.1 on 2024-04-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_signin_model_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin_model',
            old_name='users',
            new_name='user',
        ),
    ]
