# Generated by Django 4.1 on 2024-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_signin_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_addr', models.FileField(upload_to='documents/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
