# Generated by Django 4.1 on 2024-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_rename_user_signin_model_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin_model',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signin_model',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
