# Generated by Django 4.1 on 2024-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_userprofile_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin_model',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
