# Generated by Django 4.1 on 2024-04-05 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0007_signn_model_delete_sign_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin_model',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='signn_model',
        ),
    ]
