# Generated by Django 4.1 on 2024-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_signin_model_delete_signn_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin_model',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
