# Generated by Django 4.1 on 2024-04-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0013_sign_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
