# Generated by Django 4.1 on 2024-04-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0014_alter_sign_model_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_model',
        ),
    ]
