# Generated by Django 4.1 on 2024-04-09 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0015_delete_sign_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('suggest', models.CharField(max_length=200)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggest_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
