# Generated by Django 4.1 on 2024-04-09 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0017_alter_suggestion_model_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion_model',
            name='users',
        ),
        migrations.AddField(
            model_name='suggestion_model',
            name='users',
            field=models.ManyToManyField(related_name='suggest_fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
