# Generated by Django 4.1 on 2024-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0019_delete_suggestion_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin_model',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
